version: '3.2'
services:
  db:
    build:
      dockerfile: db-backend.dockerfile
      context: ./
    environment:
      - POSTGRES_PASSWORD=postgrespwd
    ports:
      - "5432:5432"
    volumes:
      # The database can be wiped with sudo -i sh -c 'rm -rf /var/lib/docker/volumes/docker_pgdata/_data/*'
      - "pgdata:/var/lib/postgresql/data"
  homesearch-python:
    build:
      dockerfile: homesearch.dockerfile
      context: ./
    environment:
      - PYTHONPATH=./
      - FLASK_ENV=development
      - DB_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - "./data:/homesearch/data"
      - "./server:/homesearch/server:ro"
      - "./zoopla:/homesearch/zoopla:ro"
      - "./utils:/homesearch/utils:ro"
      - "./metadata:/homesearch/metadata:ro"
volumes:
  pgdata: