version: '3.2'
services:
  db:
    build:
      dockerfile: db-backend.dockerfile
      context: ./
    environment:
      - POSTGRES_PASSWORD=postgrespwd
    volumes:
      # The database can be wiped with sudo -i sh -c 'rm -rf /var/lib/docker/volumes/docker_pgdata/_data/*'
      - "pgdata:/var/lib/postgresql/data"
      - "./data:/homesearch/data"
  homesearch-python:
    build:
      dockerfile: homesearch.dockerfile
      context: ./
    environment:
      - PYTHONPATH=./
      - FLASK_ENV=development
      - DB_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - "./data:/homesearch/data"
      - "./server:/homesearch/server:ro"
      - "./rightmove:/homesearch/rightmove:ro"
      - "./zoopla:/homesearch/zoopla:ro"
      - "./utils:/homesearch/utils:ro"
      - "./metadata:/homesearch/metadata:ro"
  ui:
    build:
      context: ./ui
    ports:
      - "1234:1234"
    volumes:
      - ./ui/src:/ui/src
      - ./ui/static:/ui/static
      - /ui/node_modules
      - /ui/dist
      - /ui/.cache
volumes:
  pgdata: